# Generated by Django 6.1.1 on 2026-09-05 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('reservation_ready', 'Reserved copy ready'), ('reservation_expired', 'Reservation expired'), ('fine_charged', 'Fine charged'), ('fine_cleared', 'Fine cleared'), ('general', 'Notice')], default='general', max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Optional path within the site, for example /my-loans/.', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notification_by_user_state')],
            },
        ),
    ]
