# Generated by Django 6.1.1 on 2026-09-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('loan_duration_days', models.PositiveIntegerField(default=14, help_text='Standard loan window granted for borrowed titles in days.')),
                ('max_books_per_student', models.PositiveIntegerField(default=3, help_text='Maximum simultaneous active loans permitted per student account.')),
                ('fine_rate_per_day', models.DecimalField(decimal_places=2, default=50.0, help_text='Overdue fine penalty accrued per calendar day late in Naira (₦).', max_digits=6)),
                ('allow_student_reservations', models.BooleanField(default=True, help_text='Enable self-service queue holds on checked-out books.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Suspend public transactions for scheduled maintenance operations.')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Idle session inactivity duration before re-authentication is enforced.')),
                ('api_access_enabled', models.BooleanField(default=True, help_text='Enable authenticated REST API access for external institutional systems.')),
                ('api_key_primary', models.CharField(default='ath_live_8f93e2b10a9c4d7e8b9101112', help_text='Primary institutional bearer token.', max_length=64)),
                ('webhook_url', models.URLField(blank=True, default='https://api.athenaeum.edu/webhooks/circulation', help_text='Endpoint receiving automated webhook event payloads.')),
                ('subscription_tier', models.CharField(default='Enterprise Academic Pro', help_text='Active institution license subscription tier.', max_length=50)),
                ('storage_allocated_gb', models.PositiveIntegerField(default=50, help_text='Total cloud storage quota allocated in Gigabytes.')),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=6.85, help_text='Current storage consumption in Gigabytes.', max_digits=5)),
                ('max_active_members', models.PositiveIntegerField(default=5000, help_text='Contracted member account threshold.')),
            ],
            options={
                'verbose_name': 'Enterprise System Configuration',
                'verbose_name_plural': 'Enterprise System Configuration',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('notify_email_loans', models.BooleanField(default=True, help_text='Receive email confirmation upon checkout and renewal.')),
                ('notify_email_overdue', models.BooleanField(default=True, help_text='Receive urgent alerts when borrowed titles approach due dates.')),
                ('notify_email_digest', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Summary email frequency for library activities and holds.', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD (ISO)'), ('DD/MM/YYYY', 'DD/MM/YYYY (UK)'), ('MM/DD/YYYY', 'MM/DD/YYYY (US)')], default='YYYY-MM-DD', max_length=20)),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Two-factor authentication requirement status.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
