# Generated by Django 6.1.1 on 2026-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Optional open-access PDF or EPUB document for direct reading/download.', upload_to='book_digital/'),
        ),
        migrations.AddField(
            model_name='book',
            name='digital_url',
            field=models.URLField(blank=True, help_text='Optional direct link to an online edition, Project Gutenberg, or an external repository.', max_length=500),
        ),
    ]
