# Generated by Django 6.1.1 on 2026-09-05 11:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('borrow', 'Book borrowed'), ('return', 'Book returned'), ('renew', 'Loan renewed'), ('reserve', 'Book reserved'), ('reservation_cancel', 'Reservation cancelled'), ('fine_paid', 'Fine marked paid'), ('book_create', 'Book added'), ('book_update', 'Book edited'), ('book_withdraw', 'Book withdrawn from catalogue'), ('book_delete', 'Book deleted'), ('role_change', 'Role changed')], db_index=True, max_length=32)),
                ('target', models.CharField(help_text='What was acted on, written out as text at the time.', max_length=255)),
                ('detail', models.TextField(blank=True, help_text='Anything else worth keeping, such as what changed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='The day this book is due back. Fines start the day after.')),
                ('returned_date', models.DateTimeField(blank=True, help_text='Left empty while the book is still out on loan.', null=True)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0, help_text='How many times this loan has been extended.')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged on return if the book was late.', max_digits=8)),
                ('fine_paid', models.BooleanField(default=False, help_text='Ticked by a librarian once the fine has been settled.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='catalog.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_date'],
                'indexes': [models.Index(fields=['student', 'returned_date'], name='loan_by_student_and_state')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_date__isnull', True)), fields=('student', 'book'), name='one_active_loan_per_student_per_book'), models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='fine_amount_not_negative'), models.CheckConstraint(condition=models.Q(('returned_date__isnull', True), ('returned_date__gte', models.F('borrowed_date')), _connector='OR'), name='returned_after_borrowed')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Copy available'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notified_date', models.DateTimeField(blank=True, null=True)),
                ('expires_date', models.DateTimeField(blank=True, help_text='When the offer of a copy runs out.', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reserved_date'],
                'indexes': [models.Index(fields=['book', 'status'], name='reservation_by_book_state')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'notified'])), fields=('student', 'book'), name='one_active_reservation_per_student_per_book')],
            },
        ),
    ]
